# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
<<<<<<< HEAD
  repository: r.cfcr.io/guysaltoncf/helm-sample-app-go
  tag: latest
  pullSecret: cfcr
=======
  repository: r.cfcr.io/anna-codefresh/helm-sample-app-go
>>>>>>> ebe327bc13720d5ae998c04b77b7583fc4581756
service:
  name: my-example-helm-app
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
